#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Expected 1 paramenter but got $#" >&2
  exit 1
fi

FILE_NAME="${MACROSES_HOME%/}/$1"

if [ ! -f "$FILE_NAME" ]; then
  echo "Can not find file $FILE_NAME" >&2
  exit 2
fi

if [ -L "$FILE_NAME" ]; then
  echo "${FILE_NAME} is a symbolic link to $(readlink -f "${FILE_NAME}")" >&2
else
  find "${MACROSES_HOME}" -type l \
    | while read SYMLINK; do
        TARGET="$(readlink -f "$SYMLINK")"
        if [ "x$TARGET" = "x${FILE_NAME}" ]; then
          rm -i "${SYMLINK}"
        fi
      done;
fi

rm "$FILE_NAME"
