#!/bin/sh

command="ls -lh \
            --dereference-command-line-symlink-to-dir \
            --color=always \
            ${MACROSES_HOME}"

if [ "$1" = "p" ]; then
  USE_PAGER=1
  shift
fi

if [ $# -gt 0 ]; then
  command="$command | grep \"$*\""
fi

if [ -n "$USE_PAGER" ]; then
  command="$command \
             | less --LONG-PROMPT \
                    --RAW-CONTROL-CHARS \
                    --status-column \
                    --CLEAR-SCREEN "
fi

eval "$command"
