#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Expected 1 parameter but got $#" >&2
  exit 1
fi

filename="${MACROSES_HOME%/}/$1"

if [ -f "$filename" ]; then
  echo "File $filename is already exists" >&2
  exit 2;
fi

touch "$filename" \
  && chmod +x "$filename"

# If stdin is open, write macros from stdin
# else open vim
if [ -t 0 ]; then
  vim "$filename"
else 
  stdin=''
  while read line; do
    stdin="${stdin}${line}\n"
  done
  stdin="${stdin}"
  echo "$stdin"
  echo "$stdin" >"$filename"
fi
