#!/bin/sh

command="ls -lh \
            --dereference-command-line-symlink-to-dir \
            --color=always \
            ${MACROSES_HOME}"

if [ $# -gt 0 ]; then
  $command | grep "$@"
else
  $command
fi
