#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Expected 1 paramenter but got $#" >&2
  exit 1
fi

filename="${MACROSES_HOME%/}/$1"

if [ ! -f $filename ]; then
  echo "Can not find file $filename" >&2
  exit 2
fi

rm -f "$filename"
